<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.5.16</version>
		<relativePath/>
	</parent>

	<groupId>by.yurnerix</groupId>
	<artifactId>ms-account-reservation</artifactId>
	<version>1.0.1-SNAPSHOT</version>

	<properties>
		<java.version>21</java.version>
		<lombok.version>1.18.46</lombok.version>
		<openapi-generator.version>7.24.0</openapi-generator.version>
	</properties>

	<dependencies>

		<!-- Lombok -->
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>${lombok.version}</version>
			<scope>compile</scope>
		</dependency>

		<!-- Spring Web -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<!-- Spring Bean Validation -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-validation</artifactId>
		</dependency>

		<!-- Spring Actuator -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

		<!-- Spring Data JPA -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>

		<!-- PostgreSQL -->
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<scope>runtime</scope>
		</dependency>

		<!-- Liquibase -->
		<dependency>
			<groupId>org.liquibase</groupId>
			<artifactId>liquibase-core</artifactId>
		</dependency>

		<!-- Spring Boot Test -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.junit.platform</groupId>
			<artifactId>junit-platform-launcher</artifactId>
			<scope>test</scope>
		</dependency>

	</dependencies>

	<build>

		<plugins>

			<!-- Lombok -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>

				<configuration>
					<annotationProcessorPaths>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>${lombok.version}</version>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>

			<!-- Spring Boot Maven Plugin -->
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>


			<!-- OpenAPI Generator -->
			<plugin>
				<groupId>org.openapitools</groupId>
				<artifactId>openapi-generator-maven-plugin</artifactId>
				<version>${openapi-generator.version}</version>

				<executions>
					<execution>
						<id>generate-ms-upgrade-api</id>

						<phase>generate-sources</phase>

						<goals>
							<goal>generate</goal>
						</goals>

						<configuration>

							<!-- Исходная OpenAPI-спецификация -->
							<inputSpec>
								${project.basedir}/src/main/resources/ms-upgrade-api.yaml
							</inputSpec>

							<!-- Генератор серверного Spring API -->
							<generatorName>spring</generatorName>
							<library>spring-boot</library>

							<!-- Генерация только в target -->
							<output>
								${project.build.directory}/generated-sources/openapi
							</output>

							<!-- Пакет API-интерфейсов -->
							<apiPackage>
								by.yurnerix.msaccountreservation.generated.api
							</apiPackage>

							<!-- Пакет DTO -->
							<modelPackage>
								by.yurnerix.msaccountreservation.generated.dto
							</modelPackage>

							<!-- Пакет служебных классов генератора -->
							<invokerPackage>
								by.yurnerix.msaccountreservation.generated
							</invokerPackage>

							<!-- ClientStatus из OpenAPI станет ClientStatusDto. Это отделяет API enum от Entity enum ClientStatus -->
							<modelNameSuffix>Dto</modelNameSuffix>

							<!-- Сгенерированные тесты и документация не нужны -->
							<generateApiTests>false</generateApiTests>
							<generateModelTests>false</generateModelTests>
							<generateApiDocumentation>false</generateApiDocumentation>
							<generateModelDocumentation>false</generateModelDocumentation>

							<!-- Добавляет generated sources в Maven compilation -->
							<addCompileSourceRoot>true</addCompileSourceRoot>

							<configOptions>

								<!-- Генерировать только API-интерфейсы -->
								<interfaceOnly>true</interfaceOnly>

								<!-- Не создавать пустые default-реализации методов -->
								<skipDefaultInterface>true</skipDefaultInterface>

								<!-- Использовать jakarta.* для Spring Boot 3 -->
								<useSpringBoot3>true</useSpringBoot3>

								<!-- Генерировать Bean Validation-аннотации -->
								<useBeanValidation>true</useBeanValidation>
								<performBeanValidation>true</performBeanValidation>

								<!-- Возвращать ResponseEntity -->
								<useResponseEntity>true</useResponseEntity>

								<!-- Создать ClientsApi на основании тега Clients -->
								<useTags>true</useTags>

								<!-- Не использовать JsonNullable -->
								<openApiNullable>false</openApiNullable>

								<!-- Использовать java.time.OffsetDateTime -->
								<dateLibrary>java8</dateLibrary>

								<!-- Не генерировать SpringDoc/Swagger-аннотации -->
								<documentationProvider>none</documentationProvider>
								<annotationLibrary>none</annotationLibrary>

								<!-- Стабильный сгенерированный код без даты генерации -->
								<hideGenerationTimestamp>true</hideGenerationTimestamp>

							</configOptions>

						</configuration>
					</execution>
				</executions>
			</plugin>

		</plugins>

	</build>

</project>