APPLICATION_NAME=ms-account-reservation
SERVER_PORT=8080

DATABASE_HOST=localhost
DATABASE_PORT=5432
DATABASE_NAME=account_reservation
DATABASE_USER=postgres
DATABASE_PASSWORD=asterisk

LIQUIBASE_ENABLED=true
LIQUIBASE_CHANGE_LOG=classpath:db/changelog/db.changelog-master.yaml
LIQUIBASE_SCHEMA=public

JPA_DDL_AUTO=validate
JPA_SHOW_SQL=false
JPA_FORMAT_SQL=true

