APPLICATION_NAME=ms-account-reservation
SERVER_PORT=8080

DATABASE_HOST=localhost
DATABASE_PORT=5432
DATABASE_NAME=account_reservation
DATABASE_USER=postgres
DATABASE_PASSWORD=asterisk

LIQUIBASE_ENABLED=true
LIQUIBASE_CHANGE_LOG=classpath:db/changelog/db.changelog-master.yaml
LIQUIBASE_DEFAULT_SCHEMA=public

JPA_DDL_AUTO=validate
JPA_SHOW_SQL=false
JPA_FORMAT_SQL=true

LOG_LEVEL_ROOT=INFO
LOG_LEVEL_APPLICATION=DEBUG
LOG_FILE_PATH=logs

MANAGEMENT_SERVER_PORT=8081
MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,threaddump
MANAGEMENT_HEALTH_SHOW_DETAILS=never
SHUTDOWN_TIMEOUT=20s

CURRENCY_CLIENT_ENABLED=true
CURRENCY_CLIENT_BASE_URL=https://v6.exchangerate-api.com/v6
CURRENCY_CLIENT_API_KEY=
CURRENCY_CLIENT_CONNECT_TIMEOUT=2s
CURRENCY_CLIENT_READ_TIMEOUT=5s

CURRENCY_CLIENT_RETRY_ENABLED=true
CURRENCY_CLIENT_RETRY_MAX_ATTEMPTS=3
CURRENCY_CLIENT_RETRY_INITIAL_INTERVAL=200ms
CURRENCY_CLIENT_RETRY_MULTIPLIER=2.0
CURRENCY_CLIENT_RETRY_MAX_INTERVAL=2s

CURRENCY_CLIENT_HEALTH_ENABLED=true
